pub_struct!(ABS {
    abs1_discharge_care_provider: Option<String>,
    abs2_transfer_medical_service_code: Option<String>,
    abs3_severity_of_illness_code: Option<String>,
    abs4_date_time_of_attestation: Option<String>,
    abs5_attested_by: Option<String>,
    abs6_triage_code: Option<String>,
    abs7_abstract_completion_date_time: Option<String>,
    abs8_abstracted_by: Option<String>,
    abs9_case_category_code: Option<String>,
    abs10_caesarian_section_indicator: Option<String>,
    abs11_gestation_category_code: Option<String>,
    abs12_gestation_period_weeks: Option<String>,
    abs13_newborn_code: Option<String>,
    abs14_stillborn_indicator: Option<String>,
});
