pub_struct!(ACC {
    acc1_accident_date_time: Option<String>,
    acc2_accident_code: Option<String>,
    acc3_accident_location: Option<String>,
    acc4_auto_accident_state: Option<String>,
    acc5_accident_job_related_indicator: Option<String>,
    acc6_accident_death_indicator: Option<String>,
    acc7_entered_by: Option<String>,
    acc8_accident_description: Option<String>,
    acc9_brought_in_by: Option<String>,
    acc10_police_notified_indicator: Option<String>,
    acc11_accident_address: Option<String>,
    acc12_degree_of_patient_liability: Option<String>,
    acc13_accident_identifier: Option<Vec<String>>,
});
