pub struct BPX {
    bpx1_set_id: String,
    bpx2_bp_dispense_status: String,
    bpx3_bp_status: String,
    bpx4_bp_date_time_of_status: String,
    bpx5_bc_donation_id: Option<String>,
    bpx6_bc_component: Option<String>,
    bpx7_bc_donation_type_intended_use: Option<String>,
    bpx8_cp_commercial_product: Option<String>,
    bpx9_cp_manufacturer: Option<String>,
    bpx10_cp_lot_number: Option<String>,
    bpx11_bp_blood_group: Option<String>,
    bpx12_bc_special_testing: Option<Vec<String>>,
    bpx13_bp_expiration_date_time: Option<String>,
    bpx14_bp_quantity: String,
    bpx15_bp_amount: Option<String>,
    bpx16_bp_units: Option<String>,
    bpx17_bp_unique_id: Option<String>,
    bpx18_bp_actual_dispensed_to_location: Option<String>,
    bpx19_bp_actual_dispensed_to_address: Option<String>,
    bpx20_bp_dispensed_to_receiver: Option<String>,
    bpx21_bp_dispensing_individual: Option<String>,
}
