pub struct PD1 {
    pd1_1_living_dependency: Option<Vec<String>>,
    pd1_2_living_arrangement: Option<String>,
    pd1_3_patient_primary_facility: Option<Vec<String>>,
    pd1_4_patient_primary_care_provider_name_and_id_no: Option<String>,
    pd1_5_student_indicator: Option<String>,
    pd1_6_handicap: Option<String>,
    pd1_7_living_will_code: Option<String>,
    pd1_8_organ_donor_code: Option<String>,
    pd1_9_separate_bill: Option<String>,
    pd1_10_duplicate_patient: Option<Vec<String>>,
    pd1_11_publicity_code: Option<String>,
    pd1_12_protection_indicator: Option<String>,
    pd1_13_protection_indicator_effective_date: Option<String>,
    pd1_14_place_of_worship: Option<Vec<String>>,
    pd1_15_advance_directive_code: Option<Vec<String>>,
    pd1_16_immunization_registry_status: Option<String>,
    pd1_17_immunization_registry_status_effective_date: Option<String>,
    pd1_18_publicity_code_effective_date: Option<String>,
    pd1_19_military_branch: Option<String>,
    pd1_20_military_rank_grade: Option<String>,
    pd1_21_military_status: Option<String>,
    pd1_22_advance_directive_last_verified_date: Option<String>,
}
